name: Prettier

on: [push, pull_request]

jobs:
  Prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Lint code with prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md}
